# Default values for test-app
replicaCount: 3

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Custom configuration
app:
  name: test-app
  environment: production
  
# Health checks
healthCheck:
  enabled: true
  path: /
  initialDelaySeconds: 30
  periodSeconds: 10
