apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-gitops
  namespace: argocd
  labels:
    app: test-app
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/sandeep0507/mcp-deploy-repo.git
    targetRevision: HEAD
    path: helm/test-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "3"
        - name: app.environment
          value: "production"
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
