name: ArgoCD Sync Webhook

on:
  push:
    branches: [ main ]
    paths: [ 'helm/redis/**' ]
  workflow_dispatch:

jobs:
  sync-argocd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'
        
    - name: Install Minikube
      uses: medyagh/gimme-action@v1
      with:
        version: 1.21.0
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status
        
    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
        
    - name: Port forward ArgoCD
      run: |
        kubectl port-forward svc/argocd-server -n argocd 8080:443 &
        sleep 10
        
    - name: Get ArgoCD admin password
      run: |
        kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d > argocd-password.txt
        echo "ArgoCD admin password saved"
        
    - name: Login to ArgoCD
      run: |
        argocd login localhost:8080 --username admin --password $(cat argocd-password.txt) --insecure
        
    - name: Create or Update ArgoCD Application
      run: |
        argocd app create redis-gitops \
          --repo https://github.com/SKSTAE/mcp-deploy-repo \
          --path helm/redis \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace redis-prod \
          --sync-policy automated \
          --auto-prune \
          --self-heal \
          --upsert || true
        
    - name: Sync Application
      run: |
        argocd app sync redis-gitops --force
        
    - name: Verify Deployment
      run: |
        kubectl get pods -n redis-prod
        kubectl get services -n redis-prod
        kubectl describe deployment redis -n redis-prod
