name: Deploy Redis to Minikube

on:
  push:
    branches: [ main ]
    paths: [ 'helm/redis/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'helm/redis/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'
        
    - name: Install Minikube
      uses: medyagh/gimme-action@v1
      with:
        version: 1.21.0
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status
        
    - name: Create Redis namespace
      run: |
        kubectl create namespace redis --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Deploy Redis with Helm
      run: |
        helm upgrade --install redis ./helm/redis \
          --namespace redis \
          --set namespace=redis \
          --wait --timeout=5m
          
    - name: Verify deployment
      run: |
        kubectl get pods -n redis
        kubectl get services -n redis
        
    - name: Test Redis connection
      run: |
        kubectl run redis-test --image=redis:alpine --rm -it --restart=Never -- redis-cli -h redis-service.redis.svc.cluster.local ping
