name: Deploy to Minikube

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node (for potential build steps)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.4'

      - name: Configure kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Helm upgrade/install
        run: |
          helm upgrade --install mcp-server ./helm/mcp-server \
            --namespace mcp --create-namespace \
            --set image.repository=${{ vars.IMAGE_REPOSITORY || 'ghcr.io/OWNER/REPO' }} \
            --set image.tag=${{ vars.IMAGE_TAG || 'latest' }} \
            --set service.port=3000 \
            --set service.targetPort=3000
